[package]
name = "miracle"
description = "Placeholder crate, coming soon..."
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/fwcd/miracle"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
